### ISSUE TITLE
name: lostruct?

### ISSUE THREAD

**Issue by petrelharp** [jguhlin/lostruct-py#5]
If you agree, I think this might as well be called `lostruct` instead of `lostructpy`, although if you're wanting to distribute it I'd like to be a co-maintainer?

**Comment by jguhlin** [comment]
Sure, not sure how I can add you as a co-maintainer? But happy to do so. I can rename it and release a new version, not sure if it will wipe zenodo info or not.

**Comment by petrelharp** [comment]
Well, the name of the python package can be decoupled from the github repository name - I think the repository name is good, but you could call the python package `lostruct`. This shouldn't mess with zenodo?  To be a co-maintainer, make me a collaborator on this repository, and if/when it's uploaded to other places (eg PyPI) somehow making me a co-maintainer there. (not sure how to do this, but it's possible...) If you aren't comfortable with any of this, happy to discuss.

**Comment by jguhlin** [comment]
Nah, I'm comfortable. You've been a huge help and all I've done is port some code over.

I'll work on changing the python name and push it back out to pypi, probably version 0.0.4 if that makes sense. PyPi has author and maintainer emails, but do not support lists. So we could do you as author and me as maintainer, or vice-versa? Or list it in freeform in the README.md of the repo which it uses as it's description (should do this anyways, want to add your name as a PR?)

**Comment by jguhlin** [comment]
Collaborator invite has been sent. Will probably be later today / tomorrow before I get the python package name changed.

**Comment by petrelharp** [comment]
Looks to me like we could both be "Owners" on PyPI
![Screenshot from 2020-08-24 16-02-08](https://user-images.githubusercontent.com/1046249/91104744-31aebb00-e623-11ea-8b7f-9e7113ad3562.png)

**Comment by petrelharp** [comment]
I'm happy with you being author/maintainer, though...

**Comment by jguhlin** [comment]
Oh nice. I've been using setup.py to set all the pypi stuff, but will def do that.

**Comment by jguhlin** [comment]
Done. Version 0.0.4 is released, also with get_pc_dists now properly multithreading automatically. You should be set up in pypi, let me know if not!
